### ISSUE TITLE
webview onReceivedSslError

### ISSUE THREAD

**Issue by xlf2630** [udesk/UdeskSDK-Android#10]
这个问题竟然被注释掉了，原因是上传Google play被拒！国内应用上传play应该是少数吧
建议对这个问题的处理可以再考虑下，并且对于可能出现的问题在常见问题中给出提示。

**Comment by gjyaiya** [comment]
+1

**Comment by jiejunping** [comment]
我们提供的url 保证https 安全的，  打开Google play会被拒 ，onReceivedSslError 就注释了。，
