### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by gjyaiya** [udesk/UdeskSDK-Android#12]
1. Bugly能否去掉呢? 版本太久了
2. 三方库做成provide依赖吧?
3. 能否上传到maven?

**Comment by MartinLi2015** [comment]
同问

**Comment by jiejunping** [comment]
Bugly 集成时，是可以去掉， 注释掉编译不过的初始化代码就可以。 

如果udesksdk  第三库和app 中有相同的第三方库是会方便很多。不出现相同的情况也是很多的，这会造成， 开发者疏忽时， 最后运行时没加入。 出于风险考虑，在编译的时候，产生重复冲突修改来保证。

sdk 带有很多界面， 方便手动修改界面元素， 就一直没做maven依赖。  等后续配置功能完善后， 会考虑做的。
