### ISSUE TITLE
关于sdk中的provider

### ISSUE THREAD

**Issue by xlf2630** [udesk/UdeskSDK-Android#14]
udesk作为一个三方sdk，所定义的provider不应该占用host app 的 applicationId，建议加一个专用后缀。

目前sdk中定义的provider 的 authorities 是applicationId + ”.fileprovider”，不合适

**Comment by jiejunping** [comment]
为了保证 authority要求必须是唯一， 当时就用host app 的 applicationId，  没有进一步考虑到， 谢谢你提出的意见，  下个版本会加上。
