### ISSUE TITLE
发送商品链接

### ISSUE THREAD

**Issue by zhujunjun** [udesk/UdeskSDK-Android#4]
点击商品链接信息右下角的“发送链接”按钮后，消息左边一直在loading 图标中，并且后续发送的消息也是显示loading图标。而且客服那里也收到了这些消息，但是loading状态一直没消失。
![bitmap_screenshot_1](https://cloud.githubusercontent.com/assets/17331613/21215913/ee0ec5d6-c2de-11e6-846f-133453872aca.png)

**Comment by jiejunping** [comment]
问题已解决。很抱歉这么久才回复里，升级最新版本。
